POST http://secretsantafier.com/api/group-register
Content-Type: application/json

{
    "group": {
        "name": "Boomers",
        "admin": "Jimbob",
        "adminEmail": "blah@mail",
        "pwd": "blahblah222"
    },
    "members": [
        {
            "name": "Billy",
            "email": "eryanpatterson@gmail.com"
        },
        {
            "name": "Sue",
            "email": "eryanpatterson@gmail.com"
        }
    ]
}