POST https://secretsantafier.com/api/group-register
Content-Type: application/json

{
    "group": {
        "name": "The Taters",
        "admin": "Bob Evans",
        "adminEmail": "blah@mail",
        "exchangeDate": "Dec, 2 2021",
        "spendLimit": 52
    },
    "members": [
        {
            "name": "Tabitha",
            "email": "eryanpatterson@gmail.com"
        },
        {
            "name": "Tariq",
            "email": "eryanpatterson@gmail.com"
        },
        {   
            "name": "Manfreda",
            "email": "raekpatterson@gmail.com"
        }
    ]
}

###

POST https://secretsantafier.com/api/verify-email
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGFyaXEiLCJlbWFpbCI6ImVyeWFucGF0dGVyc29uQGdtYWlsLmNvbSIsInZlcmlmaWVkIjpmYWxzZSwiX2lkIjoiNjE4ZWEyOGFjYmUwMTY3NjZmZjcyOGI5IiwiaWF0IjoxNjM2NzM3Njc0fQ.JDs1K8Q_aPw34DW-yk5cU1dswfXC9bVzXQdWXlFpMkc"
}